# -*- coding: utf-8 -*-
"""custom_encoder_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdN34DlaU8k8JG0aNdKnTFJq4blyb7Zk

# Custom Speech Encoder v2
**Architecture**: Conv stem → 6-layer Transformer with sinusoidal PE

**Training objectives (3 losses):**
- MSE reconstruction loss (0.4) — captures acoustic detail, speaker identity, prosody
- CTC loss on characters (0.4) — forces phoneme/linguistic structure in the latent
- InfoNCE contrastive loss (0.2) — makes the latent space robust via augmentation

**Output**: `(B, T, 768)` — drop-in replacement for your existing ModalityAdapter input

## 1. Install dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install torch torchaudio transformers datasets librosa soundfile \
#              pandas numpy tqdm tensorboard torchinfo

"""## 2. Config — all hyperparameters in one place"""

import torch

# ── Audio ──────────────────────────────────────────────────────────────────
MEL_SR       = 22050
N_MELS       = 80
N_FFT        = 1024
HOP_LENGTH   = 256
WIN_LENGTH   = 1024
FMIN         = 0.0
FMAX         = 8000.0
MAX_DURATION = 10.0          # seconds — clips longer than this are truncated
MAX_MEL_LEN  = int(MAX_DURATION * MEL_SR / HOP_LENGTH)  # ~862 frames

# ── Encoder architecture ───────────────────────────────────────────────────
HIDDEN_DIM    = 768
ENCODER_HEADS = 12
ENCODER_LAYERS= 6
FFN_DIM       = 3072          # 4 * HIDDEN_DIM
DROPOUT       = 0.1

# ── CTC head ───────────────────────────────────────────────────────────────
# LJSpeech characters + blank token
CHARS = list(" abcdefghijklmnopqrstuvwxyz',-.")
VOCAB = {c: i+1 for i, c in enumerate(CHARS)}   # 1-indexed; 0 = CTC blank
VOCAB_SIZE = len(CHARS) + 1                      # +1 for blank

# ── Training ───────────────────────────────────────────────────────────────
BATCH_SIZE   = 16
LR           = 3e-4
WARMUP_STEPS = 500
MAX_STEPS    = 20000
GRAD_ACCUM   = 2
FP16         = True
SAVE_EVERY   = 2000
LOG_EVERY    = 100

# ── Loss weights ───────────────────────────────────────────────────────────
W_RECON      = 0.4
W_CTC        = 0.4
W_CONTRAST   = 0.2
TEMP         = 0.07           # InfoNCE temperature

# ── Paths ──────────────────────────────────────────────────────────────────
DATA_ROOT    = 'LJSpeech-1.1'
TRAIN_CSV    = 'train.csv'
VAL_CSV      = 'val.csv'
OUTPUT_DIR   = 'encoder_v2_checkpoints'

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
print(f'MAX_MEL_LEN: {MAX_MEL_LEN}')
print(f'VOCAB_SIZE: {VOCAB_SIZE}')

"""## 3. LJSpeech download + manifest (reuse your existing split if you have it)"""

import os, pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

# ── Download if not present ─────────────────────────────────────────────────
if not Path(DATA_ROOT).exists():
    print('Downloading LJSpeech...')
    !wget -q https://data.keithito.com/data/speech/LJSpeech-1.1.tar.bz2
    !tar -xjf LJSpeech-1.1.tar.bz2
    print('Done.')
else:
    print('LJSpeech already present.')

# ── Build / load manifest ───────────────────────────────────────────────────
if not Path(TRAIN_CSV).exists():
    df = pd.read_csv(f'{DATA_ROOT}/metadata.csv', sep='|', header=None,
                     names=['id', 'transcript', 'normalized'])
    df['wav_path'] = f'{DATA_ROOT}/wavs/' + df['id'] + '.wav'
    df['text'] = df['normalized'].str.lower().str.strip()
    df['text_len'] = df['text'].str.len()
    df = df[(df['text_len'] >= 5) & (df['text_len'] <= 190)]

    train_val, test = train_test_split(df, test_size=0.10, random_state=42)
    train, val      = train_test_split(train_val, test_size=0.111, random_state=42)

    train[['id','wav_path','text']].to_csv(TRAIN_CSV, index=False)
    val[['id','wav_path','text']].to_csv(VAL_CSV, index=False)
    print(f'train: {len(train)} | val: {len(val)}')
else:
    train = pd.read_csv(TRAIN_CSV)
    val   = pd.read_csv(VAL_CSV)
    print(f'Loaded existing splits: train={len(train)}, val={len(val)}')

"""## 4. Mel spectrogram + augmentation helpers"""

import torch
import torchaudio
import torchaudio.transforms as T

# ── Mel transform ───────────────────────────────────────────────────────────
mel_transform = T.MelSpectrogram(
    sample_rate=MEL_SR,
    n_fft=N_FFT,
    win_length=WIN_LENGTH,
    hop_length=HOP_LENGTH,
    n_mels=N_MELS,
    f_min=FMIN,
    f_max=FMAX,
    power=1.0,
).to(device)


def wav_to_mel(wav: torch.Tensor, orig_sr: int) -> torch.Tensor:
    """(C, T) → (N_MELS, T_frames) log-mel, clamped to MAX_MEL_LEN."""
    if orig_sr != MEL_SR:
        wav = T.Resample(orig_sr, MEL_SR)(wav)
    if wav.shape[0] > 1:
        wav = wav.mean(0, keepdim=True)
    wav = wav.to(device)
    mel = mel_transform(wav).squeeze(0)           # (N_MELS, T)
    mel = torch.log(torch.clamp(mel, min=1e-5))
    # truncate or pad to MAX_MEL_LEN
    T_frames = mel.shape[1]
    if T_frames > MAX_MEL_LEN:
        mel = mel[:, :MAX_MEL_LEN]
    elif T_frames < MAX_MEL_LEN:
        pad = MAX_MEL_LEN - T_frames
        mel = torch.nn.functional.pad(mel, (0, pad), value=-11.5)  # log(1e-5)
    return mel   # (N_MELS, MAX_MEL_LEN)


# ── SpecAugment for contrastive augmentation ────────────────────────────────
def augment_mel(mel: torch.Tensor) -> torch.Tensor:
    """Apply time + freq masking for a second view of the same utterance."""
    mel = mel.clone()
    T_len = mel.shape[-1]
    # time mask: up to 10% of frames
    t_mask = max(1, int(0.10 * T_len))
    t0 = torch.randint(0, T_len - t_mask, (1,)).item()
    mel[:, t0:t0 + t_mask] = -11.5
    # freq mask: up to 15 mel bins
    f_mask = torch.randint(1, 16, (1,)).item()
    f0     = torch.randint(0, N_MELS - f_mask, (1,)).item()
    mel[f0:f0 + f_mask, :] = -11.5
    return mel


# ── Text → integer sequence ─────────────────────────────────────────────────
def text_to_ids(text: str):
    """Map string to list of vocab IDs; unknown chars silently dropped."""
    return [VOCAB[c] for c in text.lower() if c in VOCAB]


print('Mel + augment helpers ready ✓')

"""## 5. Dataset"""

import torchaudio
from torch.utils.data import Dataset, DataLoader
import torch.multiprocessing

torch.multiprocessing.set_start_method('spawn', force=True)

class LJSpeechEncoderDataset(Dataset):
    def __init__(self, csv_path: str):
        self.df = pd.read_csv(csv_path)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        wav, sr = torchaudio.load(row['wav_path'])

        mel      = wav_to_mel(wav, sr)          # (N_MELS, MAX_MEL_LEN)
        mel_aug  = augment_mel(mel)             # augmented view for contrastive
        label_ids = text_to_ids(str(row['text']))

        return {
            'mel'      : mel,
            'mel_aug'  : mel_aug,
            'label_ids': torch.tensor(label_ids, dtype=torch.long),
            'label_len': len(label_ids),
        }


def collate_fn(batch):
    mels      = torch.stack([b['mel']     for b in batch])     # (B, N_MELS, T)
    mels_aug  = torch.stack([b['mel_aug'] for b in batch])
    label_ids = torch.nn.utils.rnn.pad_sequence(
        [b['label_ids'] for b in batch], batch_first=True, padding_value=0
    )                                                           # (B, L_max)
    label_lens = torch.tensor([b['label_len'] for b in batch], dtype=torch.long)
    return mels, mels_aug, label_ids, label_lens


train_ds = LJSpeechEncoderDataset(TRAIN_CSV)
val_ds   = LJSpeechEncoderDataset(VAL_CSV)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=2, collate_fn=collate_fn, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=2, collate_fn=collate_fn, pin_memory=True)

print(f'train: {len(train_ds)} | val: {len(val_ds)}')
# quick shape check
m, ma, li, ll = next(iter(train_loader))
print(f'mel: {m.shape}, aug: {ma.shape}, label_ids: {li.shape}, lens: {ll}')

"""## 6. Custom Encoder architecture"""

import torch
import torch.nn as nn
import math


# Sinusoidal positional encoding
class SinusoidalPE(nn.Module):
    def __init__(self, d_model: int, max_len: int = 4096):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        pos = torch.arange(0, max_len).unsqueeze(1).float()
        div = torch.exp(torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer('pe', pe.unsqueeze(0))  # (1, max_len, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (B, T, d_model)
        return x + self.pe[:, :x.size(1)]


#  Conv stem (2× downsampling, mel_bins → hidden_dim)
class ConvStem(nn.Module):
    def __init__(self, n_mels: int, hidden_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            # layer 1: project mel bins to hidden_dim, no downsampling
            nn.Conv1d(n_mels, hidden_dim, kernel_size=3, padding=1),
            nn.GELU(),
            nn.LayerNorm(hidden_dim),   # applied after permute below
        )
        # separate stride-2 conv for downsampling
        self.downsample = nn.Conv1d(hidden_dim, hidden_dim,
                                    kernel_size=3, stride=2, padding=1)
        self.norm1 = nn.LayerNorm(hidden_dim)
        self.norm2 = nn.LayerNorm(hidden_dim)

    def forward(self, mel: torch.Tensor) -> torch.Tensor:
        # mel: (B, N_MELS, T)
        x = self.net[0](mel)             # (B, hidden_dim, T)
        x = self.net[1](x)               # GELU
        x = self.norm1(x.permute(0,2,1)).permute(0,2,1)  # LayerNorm on channels
        x = self.downsample(x)           # (B, hidden_dim, T/2)
        x = self.norm2(x.permute(0,2,1)).permute(0,2,1)
        return x.permute(0, 2, 1)        # (B, T/2, hidden_dim)


#  The encoder (frozen after training)
class CustomSpeechEncoder(nn.Module):
    """
    Input : (B, N_MELS, T)
    Output: (B, T/2, HIDDEN_DIM)  — compatible with ModalityAdapter
    """
    def __init__(
        self,
        n_mels      : int = N_MELS,
        hidden_dim  : int = HIDDEN_DIM,
        num_layers  : int = ENCODER_LAYERS,
        nhead       : int = ENCODER_HEADS,
        ffn_dim     : int = FFN_DIM,
        dropout     : float = DROPOUT,
    ):
        super().__init__()
        self.conv_stem = ConvStem(n_mels, hidden_dim)
        self.pos_enc   = SinusoidalPE(hidden_dim)

        layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=nhead,
            dim_feedforward=ffn_dim,
            dropout=dropout,
            activation='gelu',
            batch_first=True,
            norm_first=True,   # pre-norm (more stable)
        )
        self.transformer = nn.TransformerEncoder(layer, num_layers=num_layers)
        self.out_norm    = nn.LayerNorm(hidden_dim)

    def forward(self, mel: torch.Tensor) -> torch.Tensor:
        x = self.conv_stem(mel)      # (B, T/2, hidden_dim)
        x = self.pos_enc(x)          # + sinusoidal PE
        x = self.transformer(x)      # (B, T/2, hidden_dim)
        x = self.out_norm(x)
        return x                     # (B, T/2, 768)


#  Reconstruction decoder (training only, discarded afterward)
class ReconDecoder(nn.Module):
    """
    Symmetric decoder: (B, T/2, hidden_dim) → (B, N_MELS, T)
    Used only during training for the reconstruction loss.
    """
    def __init__(self, n_mels: int = N_MELS, hidden_dim: int = HIDDEN_DIM):
        super().__init__()
        # 2× upsample via ConvTranspose1d
        self.upsample = nn.ConvTranspose1d(hidden_dim, hidden_dim,
                                           kernel_size=3, stride=2,
                                           padding=1, output_padding=1)
        self.norm     = nn.LayerNorm(hidden_dim)
        self.proj     = nn.Conv1d(hidden_dim, n_mels, kernel_size=1)

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        # z: (B, T/2, hidden_dim)  — stop gradient from decoder back to encoder
        x = z.detach().permute(0, 2, 1)          # (B, hidden_dim, T/2)
        x = self.upsample(x)                      # (B, hidden_dim, T)
        x = self.norm(x.permute(0,2,1)).permute(0,2,1)
        x = self.proj(x)                          # (B, N_MELS, T)
        return x


# CTC head (training only)
class CTCHead(nn.Module):
    def __init__(self, hidden_dim: int = HIDDEN_DIM, vocab_size: int = VOCAB_SIZE):
        super().__init__()
        self.proj = nn.Linear(hidden_dim, vocab_size)

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        return self.proj(z)   # (B, T/2, vocab_size) — log_softmax applied in loss


#  Full training model
class SpeechEncoderTraining(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = CustomSpeechEncoder()
        self.decoder = ReconDecoder()
        self.ctc_head= CTCHead()

        self.ctc_loss  = nn.CTCLoss(blank=0, reduction='mean', zero_infinity=True)
        self.recon_loss= nn.MSELoss()

    def forward(self, mel, mel_aug, label_ids, label_lens):
        B, _, T_orig = mel.shape

        # Encode both views
        z      = self.encoder(mel)        # (B, T/2, 768)  — main view
        z_aug  = self.encoder(mel_aug)    # (B, T/2, 768)  — augmented view
        T_enc  = z.size(1)               # T/2

        # 1. Reconstruction loss (decoder uses detached z)
        mel_hat    = self.decoder(z)                         # (B, N_MELS, T)
        # decoder output may differ from T_orig by 1 frame due to stride
        min_t      = min(mel_hat.shape[-1], T_orig)
        loss_recon = self.recon_loss(mel_hat[:, :, :min_t], mel[:, :, :min_t])

        # 2. CTC loss
        log_probs   = self.ctc_head(z).log_softmax(-1)      # (B, T/2, V)
        log_probs_t = log_probs.permute(1, 0, 2)            # (T/2, B, V) — CTC wants this
        input_lens  = torch.full((B,), T_enc, dtype=torch.long, device=mel.device)
        loss_ctc    = self.ctc_loss(log_probs_t, label_ids, input_lens, label_lens)

        # 3. InfoNCE contrastive loss
        # Pool over time → (B, 768); compare z vs z_aug
        z_pool     = z.mean(dim=1)          # (B, 768)
        z_aug_pool = z_aug.mean(dim=1)      # (B, 768)

        # L2 normalise
        z_n    = nn.functional.normalize(z_pool,     dim=-1)
        z_aug_n= nn.functional.normalize(z_aug_pool, dim=-1)

        # Cosine similarity matrix (B, B)
        sim = torch.matmul(z_n, z_aug_n.T) / TEMP
        labels_c = torch.arange(B, device=mel.device)
        loss_contrast = (
            nn.functional.cross_entropy(sim, labels_c) +
            nn.functional.cross_entropy(sim.T, labels_c)
        ) / 2.0

        # Combined loss
        loss = W_RECON * loss_recon + W_CTC * loss_ctc + W_CONTRAST * loss_contrast

        return loss, {
            'total'   : loss.item(),
            'recon'   : loss_recon.item(),
            'ctc'     : loss_ctc.item(),
            'contrast': loss_contrast.item(),
        }


# Instantiate + print stats
model = SpeechEncoderTraining().to(device)

enc_params  = sum(p.numel() for p in model.encoder.parameters())  / 1e6
dec_params  = sum(p.numel() for p in model.decoder.parameters())  / 1e6
ctc_params  = sum(p.numel() for p in model.ctc_head.parameters()) / 1e6
total_train = sum(p.numel() for p in model.parameters() if p.requires_grad) / 1e6

print(f'Encoder params : {enc_params:.1f}M  ← this is what we keep')
print(f'Decoder params : {dec_params:.1f}M  (training only, discarded)')
print(f'CTC head params: {ctc_params:.1f}M  (training only, discarded)')
print(f'Total trainable: {total_train:.1f}M')

# Shape sanity check
with torch.no_grad():
    dummy_mel = torch.randn(2, N_MELS, MAX_MEL_LEN).to(device)
    z_test    = model.encoder(dummy_mel)
    print(f'\nEncoder output shape: {z_test.shape}')  # (2, ~431, 768)
    print('Expected: (2, ~431, 768) — compatible with ModalityAdapter ✓')

# CUSTOM SPEECH ENCODER — ARCHITECTURE SUMMARY

import gc
from torchinfo import summary

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("  CUSTOM SPEECH ENCODER v2 — ARCHITECTURE")

# Print full torchinfo summary
print(" Full Model Architecture:\n")
summary(
    model.encoder,
    input_data=torch.randn(1, N_MELS, MAX_MEL_LEN).to(device),
    col_names=["input_size", "output_size", "num_params", "trainable"],
    col_width=20,
    row_settings=["var_names"],
    depth=4,
    verbose=1,
)


print(" Component Breakdown:")

components = {
    "ConvStem (kept)":         model.encoder.conv_stem,
    "Positional Encoding (kept)": model.encoder.pos_enc,
    "Transformer (kept)":      model.encoder.transformer,
    "Output Norm (kept)":      model.encoder.out_norm,
    "Recon Decoder (discard)": model.decoder,
    "CTC Head (discard)":      model.ctc_head,
}

total_keep    = 0
total_discard = 0

for name, module in components.items():
    n = sum(p.numel() for p in module.parameters())
    kept = "(discard)" not in name
    tag  = "ok" if kept else "trash"
    print(f"   {tag} {name:<35} {n/1e6:>6.2f}M params")
    if kept:
        total_keep    += n
    else:
        total_discard += n

total = total_keep + total_discard
print(f"   {'Encoder (saved to .pt)':<40} {total_keep/1e6:>6.2f}M params")
print(f"   {'Training scaffolding (discarded)':<40} {total_discard/1e6:>6.2f}M params")
print(f"   {'Total (during training)':<40} {total/1e6:>6.2f}M params")
print(" Data Flow:")

print(f"   Input mel        : (B, {N_MELS}, {MAX_MEL_LEN})  ← {MAX_DURATION}s audio @ {MEL_SR}Hz")
print(f"   After ConvStem   : (B, {MAX_MEL_LEN//2}, {HIDDEN_DIM})  ← 2× time downsampled")
print(f"   After Transformer: (B, {MAX_MEL_LEN//2}, {HIDDEN_DIM})  ← {ENCODER_LAYERS} layers, {ENCODER_HEADS} heads")
print(f"   Encoder output   : (B, {MAX_MEL_LEN//2}, {HIDDEN_DIM})  → ModalityAdapter input ✓")
print()
print("   Training branches:")
print(f"   ├── Recon Decoder → (B, {N_MELS}, {MAX_MEL_LEN})   MSE loss  (weight={W_RECON})")
print(f"   ├── CTC Head      → (B, {MAX_MEL_LEN//2}, {VOCAB_SIZE})   CTC loss  (weight={W_CTC})")
print(f"   └── InfoNCE       → scalar          Contrastive (weight={W_CONTRAST})")
print()
print(" Encoder output compatible with ModalityAdapter (hidden_dim=768)")

"""## 7. Optimizer + LR scheduler"""

import torch.optim as optim
import math

optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-2,
                        betas=(0.9, 0.98), eps=1e-9)


def get_lr(step: int) -> float:
    """Linear warmup → cosine decay."""
    if step < WARMUP_STEPS:
        return step / max(1, WARMUP_STEPS)
    progress = (step - WARMUP_STEPS) / max(1, MAX_STEPS - WARMUP_STEPS)
    return max(0.05, 0.5 * (1.0 + math.cos(math.pi * progress)))


scheduler = optim.lr_scheduler.LambdaLR(optimizer, get_lr)

# Mixed precision scaler
scaler = torch.cuda.amp.GradScaler(enabled=FP16)

print('Optimizer + scheduler ready ✓')

"""## 8. Training loop"""

import os
from tqdm import tqdm
from torch.utils.tensorboard import SummaryWriter

os.makedirs(OUTPUT_DIR, exist_ok=True)
writer = SummaryWriter(log_dir=f'{OUTPUT_DIR}/tb_logs')

step          = 0
accum_step    = 0
best_val_loss = float('inf')
running       = {k: 0.0 for k in ['total','recon','ctc','contrast']}

model.train()
optimizer.zero_grad()

print(f'Starting training for {MAX_STEPS} steps...')
print(f'Effective batch size: {BATCH_SIZE * GRAD_ACCUM}')

epoch = 0
while step < MAX_STEPS:
    epoch += 1
    for batch in train_loader:
        if step >= MAX_STEPS:
            break

        mel, mel_aug, label_ids, label_lens = [
            x.to(device) for x in batch
        ]

        #  Forward + backward
        with torch.cuda.amp.autocast(enabled=FP16):
            loss, loss_dict = model(mel, mel_aug, label_ids, label_lens)
            loss = loss / GRAD_ACCUM

        scaler.scale(loss).backward()
        accum_step += 1

        # Accumulate metrics
        for k in running:
            running[k] += loss_dict[k] / GRAD_ACCUM

        # Optimizer step
        if accum_step == GRAD_ACCUM:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()
            optimizer.zero_grad()
            accum_step = 0
            step += 1

            # Logging
            if step % LOG_EVERY == 0:
                lr_now = scheduler.get_last_lr()[0] * LR
                for k, v in running.items():
                    writer.add_scalar(f'train/{k}', v / LOG_EVERY, step)
                print(f'step {step:>6}/{MAX_STEPS} | '
                      f'loss={running["total"]/LOG_EVERY:.4f} '
                      f'recon={running["recon"]/LOG_EVERY:.4f} '
                      f'ctc={running["ctc"]/LOG_EVERY:.4f} '
                      f'contrast={running["contrast"]/LOG_EVERY:.4f} '
                      f'lr={lr_now:.2e}')
                running = {k: 0.0 for k in running}

            # Validation + checkpoint
            if step % SAVE_EVERY == 0:
                model.eval()
                val_losses = {k: 0.0 for k in ['total','recon','ctc','contrast']}
                n_val = 0
                with torch.no_grad():
                    for vbatch in val_loader:
                        vm, vma, vli, vll = [x.to(device) for x in vbatch]
                        with torch.cuda.amp.autocast(enabled=FP16):
                            _, vd = model(vm, vma, vli, vll)
                        for k in val_losses:
                            val_losses[k] += vd[k]
                        n_val += 1

                for k in val_losses:
                    val_losses[k] /= n_val
                    writer.add_scalar(f'val/{k}', val_losses[k], step)

                print(f'\n>>> VAL step {step} | '
                      f'total={val_losses["total"]:.4f} '
                      f'recon={val_losses["recon"]:.4f} '
                      f'ctc={val_losses["ctc"]:.4f} '
                      f'contrast={val_losses["contrast"]:.4f}')

                # Save full checkpoint
                ckpt = {
                    'step'            : step,
                    'encoder_state'   : model.encoder.state_dict(),
                    'decoder_state'   : model.decoder.state_dict(),
                    'ctc_head_state'  : model.ctc_head.state_dict(),
                    'optimizer_state' : optimizer.state_dict(),
                    'scheduler_state' : scheduler.state_dict(),
                    'val_loss'        : val_losses['total'],
                }
                torch.save(ckpt, f'{OUTPUT_DIR}/ckpt_step{step}.pt')

                if val_losses['total'] < best_val_loss:
                    best_val_loss = val_losses['total']
                    torch.save(ckpt, f'{OUTPUT_DIR}/best.pt')
                    print(f'  ↳ New best val loss: {best_val_loss:.4f}  (saved best.pt)')

                model.train()

writer.close()
print(f'\nTraining complete. Best val loss: {best_val_loss:.4f}')

"""## 9. Export — save ONLY the encoder (everything else is discarded)"""

# Load best checkpoint
best_ckpt = torch.load(f'{OUTPUT_DIR}/best.pt', map_location=device)
model.encoder.load_state_dict(best_ckpt['encoder_state'])
model.encoder.eval()

# Save just the encoder state_dict — this replaces custom_autoencoder.pt
torch.save(
    model.encoder.state_dict(),
    f'{OUTPUT_DIR}/custom_encoder_v2.pt'
)
print(f'Encoder saved to {OUTPUT_DIR}/custom_encoder_v2.pt')
print(f'Encoder params: {sum(p.numel() for p in model.encoder.parameters())/1e6:.1f}M')

"""## 10. Inference test — verify encoder output is ModalityAdapter-compatible"""

import torch
import torch.nn as nn
import torchaudio
import pandas as pd

# MODALITY ADAPTER

class ModalityAdapter(nn.Module):
    def __init__(
        self,
        encoder_dim: int = 768,
        llm_dim: int = 2048,
        num_query_tokens: int = 32,
        num_qformer_layers: int = 2,
        nhead: int = 8,
        ffn_dim: int = 512,
    ):
        super().__init__()

        # 1. Conv downsampler
        self.conv_downsample = nn.Sequential(
            nn.Conv1d(encoder_dim, encoder_dim, kernel_size=5, stride=2, padding=2),
            nn.ReLU(),
            nn.Conv1d(encoder_dim, encoder_dim, kernel_size=5, stride=2, padding=2),
            nn.ReLU(),
        )

        # 2. Q-Former in encoder_dim (768)
        self.query_tokens = nn.Parameter(torch.randn(1, num_query_tokens, encoder_dim))
        qformer_layer = nn.TransformerDecoderLayer(
            d_model=encoder_dim,
            nhead=nhead,
            dim_feedforward=ffn_dim,
            batch_first=True,
            activation='gelu',
        )
        self.qformer = nn.TransformerDecoder(qformer_layer, num_layers=num_qformer_layers)
        self.norm = nn.LayerNorm(encoder_dim)

        # 3. Project up to LLM dim after Q-Former
        self.linear_proj = nn.Linear(encoder_dim, llm_dim)

    def forward(self, encoder_output: torch.Tensor) -> torch.Tensor:
        B = encoder_output.size(0)
        x = encoder_output.permute(0, 2, 1)           # (B, 768, T)
        x = self.conv_downsample(x)                    # (B, 768, T/4)
        x = x.permute(0, 2, 1)                        # (B, T/4, 768)
        queries = self.query_tokens.expand(B, -1, -1)  # (B, 32, 768)
        out = self.qformer(queries, memory=x)          # (B, 32, 768)
        out = self.norm(out)
        out = self.linear_proj(out)                    # (B, 32, 2048)
        return out


# LOAD TRAINED ENCODER
encoder = CustomSpeechEncoder().to(device)
encoder.load_state_dict(torch.load(f'{OUTPUT_DIR}/custom_encoder_v2.pt',
                                    map_location=device))
encoder.eval()

adapter = ModalityAdapter().to(device)
adapter.eval()

# RUN A REAL CLIP END-TO-END

sample = pd.read_csv(TRAIN_CSV).iloc[0]
wav, sr = torchaudio.load(sample['wav_path'])
mel_input = wav_to_mel(wav, sr).unsqueeze(0).to(device)  # (1, 80, 862)

with torch.no_grad():
    z            = encoder(mel_input)     # (1, ~431, 768)
    audio_tokens = adapter(z)             # (1, 32, 2048)


print('  END-TO-END SHAPE CHECK')
print(f'  Input mel        : {mel_input.shape}')    # (1, 80, 862)
print(f'  Encoder output   : {z.shape}')            # (1, ~431, 768)
print(f'  Adapter output   : {audio_tokens.shape}') # (1, 32, 2048)
print()
print(f'  Encoder stats    : min={z.min():.3f}  max={z.max():.3f}  mean={z.mean():.3f}')
print(f'  Adapter stats    : min={audio_tokens.min():.3f}  max={audio_tokens.max():.3f}  mean={audio_tokens.mean():.3f}')
print()

assert audio_tokens.shape == (1, 32, 2048), f'Shape mismatch: {audio_tokens.shape}'
print('  Shape assertion passed - ready for LLM input')
print('='*60)

# Param counts 
enc_params     = sum(p.numel() for p in encoder.parameters()) / 1e6
adapter_params = sum(p.numel() for p in adapter.parameters()) / 1e6
print(f'\n  Encoder params : {enc_params:.1f}M')
print(f'  Adapter params : {adapter_params:.1f}M')
print(f'  Combined       : {enc_params + adapter_params:.1f}M')
